name: recorder
channels:
    - conda-forge
    - defaults
    - anaconda
dependencies:
    - python=3.8
    - numpy=1.22.4
    - pysoundfile
    - av
    - scipy
    - numba
    - h5py
    - pandas
    - pyqt=5.12.3
    - pyqtgraph=0.12.3
    - pip:
        - nidaqmx
        - arrayqueues
        - pypylon
        - sounddevice
        - schedule
        - opencv-python==4.2.0.34